version: "3.9"  # optional since v1.27.0
services:
  mariadb:
    # image: mysql:8.0
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    restart: always
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/tgildero/Desktop/data/wordpress' # изменить путь
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/tgildero/Desktop/data/dbdata' # изменить путь

networks:
  app-network:
    driver: bridge
